# -*- coding: utf-8 -*-
"""Per-course data spine + substantive syllabi for the 7 IIBS-level course pages.
Lesson descriptions are grounded in each course's CEFR level and geo journey
(data/courses_geo.json). FA = 20 units, LSF = 10 units."""

# ----- shared teacher pool (real portraits in assets/teachers/) -----
TEACHERS = {
    "caitlin":  ("Caitlin",  "Strasbourg",  "French-American teacher who bridges two cultures in every class — warm, precise, and endlessly patient with first words.", "caitlin.jpg"),
    "carmele":  ("Carmèle",  "Paris",       "Parisian content creator who turns the city's everyday rituals into living lessons your phone could never teach.", "carmele.png"),
    "charline": ("Charline", "Paris",       "Native Parisian who makes pronunciation feel effortless and treats every learner like a guest at her own table.", "charline.jpg"),
    "corentin": ("Corentin", "Pau",         "Three decades teaching French — a calm, structured mentor who has guided thousands from silence to conversation.", "corentin.png"),
    "iris":     ("Iris Linza","Lyon",       "Lyon-based teacher with a gastronome's love of nuance, drawing learners into the rhythm of real French speech.", "iris.png"),
    "philippe": ("Philippe", "West Paris",  "Fifteen-plus years teaching abroad, now broadcasting live from West Paris with infectious cultural curiosity.", "philippe.jpg"),
    "shanice":  ("Shanice",  "Montpellier", "Franco-Canadian teacher from sunny Montpellier — energetic, encouraging, and a specialist in unlocking the shy.", "shanice.png"),
    "stan":     ("Stan",     "Nice",        "Niçois teacher who brings Mediterranean ease to grammar, making even the subjunctive feel like a coastal stroll.", "stan.png"),
}

# ----- per-course config -----
COURSES = {
"fa-foundation": {
    "id":"fa-foundation","name":"FA Foundation","track":"French Atelier","track_no":"Course 1 of 4",
    "level":"A0 → A1.1","entry":"A0","exit":"A1.1","units":20,"lesson_min":"85 min","group":"8–10 learners",
    "region":"Paris","new":False,
    "bg":"#10193A","accent":"#C8A560","tint":"#E7D9B8",
    "journey":"A complete beginner's first weekend in Paris.",
    "pitch":"Your very first words of French, learned not from a textbook but on the Champ-de-Mars, at a café counter, in a real Parisian queue. Twenty live lessons take you from silence to surviving a weekend in Paris.",
    "outcome":"survive in French in everyday travel situations — ask directions, order, repair a breakdown, pay, and exchange personal information",
    "spec_schedule":"Tue & Thu evenings · live",
    "price_week":"$42","price_total":"$840",
    "geo_intro":"FA Foundation unfolds entirely in Paris over one long, luminous weekend. Each unit is anchored in a real landmark — the Eiffel Tower, a bakery in the 16th, the legendary Bouillon Chartier, the Palais-Royal gardens, Shakespeare &amp; Co, Montmartre, the Canal Saint-Martin — so the language attaches itself to a place you can picture.",
    "teachers":["philippe","charline","carmele","caitlin","stan","corentin"],
    "head":"corentin",
    "next":("fa-beginner","FA Beginner","A1.1 → A1.2 · Normandy → Paris"),
    "prev":None,
    "signature":{"code":"FA0-01","title":"Se présenter à la Tour Eiffel","deck":"https://gamma.app/docs/FA0-01-Se-presenter-a-la-Tour-Eiffel-7h2ggmgt8gh1pfd?mode=doc"},
    "lessons":[
        ("Se présenter à la Tour Eiffel","At the foot of the Eiffel Tower on the Champ-de-Mars, you learn to greet, exchange names, and propose <em>tu</em> with the verb <em>s'appeler</em>. You decode the cultural codes of a first French meeting — the handshake, the <em>bonjour</em>, the eye contact. By the end you can introduce yourself to a stranger and respond when they introduce themselves.","Eiffel Tower & Champ-de-Mars"),
        ("Épeler et vérifier une information","In a bakery in the 16th arrondissement you practise the French alphabet and the sounds that trip up beginners. You ask how a word is spelled, spell your own name back, and confirm or correct using simple clarification strategies. The can-do outcome: reliably give and check spelling out loud.","Bakery, 16th arrondissement"),
        ("Demander son chemin","Lost near the Alma bridge, you learn <em>excusez-moi</em> and <em>c'est où ?</em> to ask the way. You understand short replies — left, right, straight on — and pick up vocabulary for the public places around you. You leave able to ask for and follow simple directions on a real street.","Classic café near the Alma bridge"),
        ("Réparer et commander une boisson","At a classic café you signal a communication breakdown, ask someone to repeat or slow down, and place your first simple order. These repair phrases are the safety net that keeps every later conversation afloat. You can now order a drink and recover when you don't understand.","Classic café near the Alma bridge"),
        ("Commander [1/5] — Je voudrais… c'est combien ?","Inside the bustling Bouillon Chartier you order food and drink with <em>je voudrais</em>, ask the price, and handle numbers 0–39. You taste a slice of working-class Parisian dining culture. The outcome: place a basic order and understand a simple price.","Bouillon Chartier"),
        ("Commander [2/5] — Autre chose ?","Still at Chartier, you respond to <em>Autre chose ?</em> and <em>C'est tout ?</em>, add items to your order, and stretch your numbers to 69. You read a real brasserie menu and choose with confidence. You can extend an order and react to the waiter's prompts.","Bouillon Chartier"),
        ("Proposer une sortie simple","In the Palais-Royal gardens you use <em>être</em> and the pronoun <em>y</em> to suggest an outing, then accept or decline. You reach a simple shared decision with a friend. The can-do: propose a plan and agree on it.","Palais-Royal gardens"),
        ("Accepter, refuser, préférer","Walking through the Tuileries you use <em>je préfère</em> to choose between two options and refuse politely without offence. You learn the small phrases of French agreement and gentle disagreement. You can now state a preference and settle a friendly choice.","Tuileries"),
        ("Échanger un numéro de téléphone","On the Pont des Arts you ask for and give a phone number, then verify it with <em>c'est ça ?</em>, practising numbers 70–99 and French mobile conventions. You leave able to exchange and confirm a number aloud.","Pont des Arts"),
        ("Commander [3/5] — Payer par carte","Back at a café you express hunger and thirst with <em>j'ai faim / soif</em>, order, and pay by card from start to finish. This is your first complete, self-contained transaction in French. You can run a café interaction end to end.","Classic café near the Alma bridge"),
        ("Acheter un billet, demander un prix","At the Panthéon you buy a ticket, ask the price, and pay, consolidating <em>je voudrais</em> and payment vocabulary. You discover the role monuments and museums play in French civic life. The outcome: buy entry to a cultural site unaided.","Panthéon"),
        ("Donner son email et son adresse","In the Jardin du Luxembourg you exchange email and street addresses using the possessives <em>mon, ma</em>, spelling the tricky parts and confirming details. You can now share and note down contact information clearly.","Jardin du Luxembourg"),
        ("Parler de son origine et d'où l'on habite","At Shakespeare &amp; Co you use <em>venir de</em> and <em>habiter à</em> to say where you are from and where you live, and to introduce a third person. You leave able to talk simply about your origins and home.","Shakespeare & Co"),
        ("Gérer un imprévu","On the Coulée Verte you face a closed venue and learn to propose an alternative plan and decide on the spot, drilling <em>nous sommes / ils sont</em> and booking vocabulary. The can-do: handle a small surprise and keep the day moving.","Coulée Verte"),
        ("Fixer un rendez-vous","At Bastille you propose a time and date, negotiate with <em>ça va ?</em>, confirm, and close the exchange — telling the time and using the days of the week in context. You can now make and confirm a simple appointment.","Bastille"),
        ("Commander [4/5] — Réactivation","Back in a brasserie you revisit the ordering sequence at speed: three ways to answer <em>Autre chose ?</em>, ordering one or two items, and closing politely. This consolidation builds the automaticity real conversation demands.","Bouillon Chartier"),
        ("Commander [5/5] — Je prends… l'addition","In Montmartre near the Place du Tertre you use <em>je prends</em>, react when an item is unavailable, and ask for the bill — a fluent, complete restaurant interaction. You leave able to dine out and pay from start to finish.","Montmartre & Place du Tertre"),
        ("Exprimer et justifier une préférence","On the terraces of Montmartre you choose between two options, say <em>je préfère</em>, and justify with <em>parce que c'est + adjectif</em>, practising adjective agreement and opinion exchange. The outcome: give a short reasoned preference.","Montmartre & Place du Tertre"),
        ("Arrivée — présentation et orientation [1/2]","Along the Canal Saint-Martin you chain two micro-tasks — introducing yourself and asking the way — adding a repair strategy if needed. This best-of review of units 1–3 proves how far you've come.","Canal Saint-Martin"),
        ("Commander, payer, réparer, conclure [2/2]","Your final unit by the canal: complete a full ordering-and-payment scenario at speed, using at least one correct formula and closing politely. A best-of review of units 4–18 — and the confirmation that you can now survive a weekend in Paris in French.","Canal Saint-Martin"),
    ],
},
"fa-beginner": {
    "id":"fa-beginner","name":"FA Beginner","track":"French Atelier","track_no":"Course 2 of 4",
    "level":"A1.1 → A1.2","entry":"A1.1","exit":"A1.2","units":20,"lesson_min":"85 min","group":"8–10 learners",
    "region":"Normandy → Paris & Versailles","new":False,
    "bg":"#1A2740","accent":"#D98C7A","tint":"#F0D2C8",
    "journey":"From the Normandy coast inland to Paris and Versailles.",
    "pitch":"You can already say bonjour — now learn to truly interact. From Étretat's chalk cliffs to the gilded halls of Versailles, twenty live lessons give you the autonomy to talk about your life, your family and your tastes.",
    "outcome":"interact with autonomy in everyday situations — locate yourself, talk about family and daily life, weather and preferences, and complete a market or museum outing",
    "spec_schedule":"Mon & Wed evenings · live",
    "price_week":"$42","price_total":"$840",
    "geo_intro":"FA Beginner travels from the Belle Époque promenade of Cabourg and the chalk cliffs of Étretat — beloved of Monet and Maupassant — through the half-timbered streets of Rouen and Honfleur (where Champlain set sail for Québec), then inland to the Palace of Versailles and the living quarters of Paris.",
    "teachers":["caitlin","shanice","iris","carmele","philippe","stan"],
    "head":"caitlin",
    "next":("fa-elementary","FA Elementary","A1.2 → A2.1 · Loire → Bordeaux → Basque"),
    "prev":("fa-foundation","FA Foundation","A0 → A1.1 · Paris"),
    "signature":None,
    "lessons":[
        ("Sur la promenade de Cabourg","On Cabourg's Belle Époque seafront you reactivate greetings and learn to locate yourself and others with <em>il y a</em> and prepositions of place. You describe a scene in front of you simply. The can-do: say where things and people are.","Cabourg Belle Époque promenade"),
        ("Dans les rues de Rouen","Among Rouen's half-timbered streets you ask and give directions with more detail, naming shops and landmarks. You handle a short street exchange with a passer-by. The outcome: navigate a French town centre by asking.","Rouen half-timbered streets"),
        ("Le port de Honfleur","In the painters' port of Honfleur — from which Champlain sailed for Québec — you talk about origins and journeys with <em>venir de</em> and <em>aller à</em>. You connect place, history and your own travels. You can now narrate where you've come from and where you're going.","Honfleur port"),
        ("Présenter sa famille","On the Deauville boardwalks you introduce your family using possessive adjectives and the verb <em>avoir</em>, describing relationships and ages. You leave able to talk about the people closest to you.","Deauville boardwalks"),
        ("Décrire les gens","Before the chalk cliffs of Étretat — Monet's subject, Maupassant's home — you describe physical appearance and character with adjectives that agree. You sketch a person in a few sentences. The can-do: describe what someone looks like and is like.","Étretat chalk cliffs"),
        ("Parler de la météo","Still on the Normandy coast you discuss the weather and the seasons, using <em>il fait</em> and <em>il y a</em> with weather expressions. You link weather to plans. You can now talk about and react to the weather.","Étretat chalk cliffs"),
        ("Une visite au château","At the Palace of Versailles you buy tickets, follow a simple guided route, and ask questions about what you see. You handle the full logistics of a cultural visit. The outcome: manage a museum or monument outing in French.","Palace of Versailles"),
        ("Décrire un lieu","In the gardens of Versailles you describe a place — its size, its features, your impression — using <em>c'est</em> and <em>il y a</em> with qualifying adjectives. You leave able to describe a space and your feelings about it.","Palace of Versailles"),
        ("La fête au village","On the Place de la Contrescarpe during a Bastille Day celebration you talk about festivities, invite someone, and accept or decline, exploring French public holidays. You can now navigate a social event and its invitations.","Place de la Contrescarpe (Bastille Day)"),
        ("Au jardin","In the Jardin des Plantes you talk about leisure and routine with the present tense of regular verbs, describing what you usually do. The can-do: describe a typical day or pastime.","Jardin des Plantes"),
        ("Le long des quais","Walking the Seine quays you express likes and dislikes with <em>aimer</em>, <em>adorer</em>, <em>détester</em>, and justify them simply. You compare your tastes with a partner. You can now talk about preferences and give a reason.","Seine quays"),
        ("Sur la Place des Vosges","In the elegant Place des Vosges you make and respond to simple suggestions, proposing an activity and arranging to meet. You leave able to organise a small outing with a friend.","Place des Vosges"),
        ("Au musée Carnavalet","Inside the Musée Carnavalet you talk about the past in the simplest way, describing what a place used to be and reacting to history. The outcome: understand and give basic information about the past.","Musée Carnavalet"),
        ("Au café du Marais","In a Marais café you order a full meal, ask about dishes, and handle the bill with growing fluency, building on Foundation's ordering skills. You can now manage a relaxed café meal with choices.","Marais café"),
        ("Une séance de cinéma","At La Cinémathèque you talk about films and tastes, propose a screening, and agree on a choice, using <em>vouloir</em> and <em>pouvoir</em>. The can-do: organise an evening out around a shared interest.","La Cinémathèque"),
        ("Au restaurant Le Train Bleu","Beneath the frescoes of Le Train Bleu at the Gare de Lyon you handle a more formal meal — booking, ordering courses, and making polite requests. You leave able to dine in a smarter setting.","Le Train Bleu, Gare de Lyon"),
        ("Au marché d'Aligre","At the lively Marché d'Aligre you buy fresh produce by weight and quantity, ask prices, and bargain gently, mastering quantities and partitive articles. The outcome: do your shopping at a French market.","Marché d'Aligre"),
        ("Raconter sa journée","You narrate your day in sequence using <em>d'abord, ensuite, après</em>, linking several simple actions. You can now tell a short, ordered account of what you did.","Seine quays"),
        ("Faire des projets","You talk about near-future plans with <em>aller + infinitif</em>, describing what you intend to do this week. The can-do: state your plans and intentions clearly.","Place des Vosges"),
        ("Bilan — une sortie complète","Your final unit chains everything into one complete outing: locate, invite, travel, visit, order and recount — a best-of review proving you can now act with real autonomy across a French day.","Palace of Versailles"),
    ],
},
"fa-elementary": {
    "id":"fa-elementary","name":"FA Elementary","track":"French Atelier","track_no":"Course 3 of 4",
    "level":"A1.2 → A2.1","entry":"A1.2","exit":"A2.1","units":20,"lesson_min":"85 min","group":"8–10 learners",
    "region":"Loire → Bordeaux → Basque Country","new":False,
    "bg":"#241A30","accent":"#9A5560","tint":"#E3C9CE",
    "journey":"A route from the Loire châteaux to the Atlantic and the Basque Country.",
    "pitch":"Move from surviving to expressing yourself. From the Renaissance gardens of Villandry to the wine quays of Bordeaux and the harbour of Saint-Jean-de-Luz, you learn to narrate, justify and describe with growing nuance.",
    "outcome":"produce language semi-guided — chain exchanges, express and justify preferences, narrate a short past event, and describe a work of art",
    "spec_schedule":"Tue & Thu evenings · live",
    "price_week":"$42","price_total":"$840",
    "geo_intro":"FA Elementary follows the great Atlantic diagonal: from Orléans and the Renaissance gardens of Villandry, through Chenonceau and the terraces of Tours, down to the vineyards and quays of Bordeaux, the Dune du Pilat, and on to the Basque coast — Bayonne, Biarritz, Saint-Jean-de-Luz and the red-pepper village of Espelette.",
    "teachers":["iris","stan","corentin","shanice","charline","caitlin"],
    "head":"iris",
    "next":("fa-intermediate","FA Intermediate","A2.1 → A2.2 · Marseille → Chamonix → Alsace"),
    "prev":("fa-beginner","FA Beginner","A1.1 → A1.2 · Normandy → Paris"),
    "signature":None,
    "lessons":[
        ("Arrivée à Orléans","In Orléans you reactivate introductions and learn to chain a longer exchange, linking several questions and answers into a real conversation. The can-do: sustain a short multi-turn dialogue.","Orléans"),
        ("Dans les jardins de Villandry","Among the Renaissance gardens of Villandry you describe a place in detail and express admiration, expanding your stock of qualifying adjectives. You leave able to describe and react to a beautiful setting.","Renaissance gardens of Villandry"),
        ("Au château de Chenonceau","At Chenonceau you ask for and give information on a guided visit, understanding a simple commentary about the past. The outcome: follow a cultural tour and ask informed questions.","Château de Chenonceau"),
        ("Sur les terrasses de Tours","On the terraces of Tours you order, recommend and react to recommendations, justifying choices with <em>parce que</em>. You can now give and respond to a simple recommendation.","Terraces of Tours"),
        ("Un déjeuner en guinguette","At a Loire guinguette you talk about food and conviviality, narrate a recent meal, and use the <em>passé composé</em> for the first time. The can-do: recount a short past experience.","Loire guinguette"),
        ("Dans le parc de Poitiers","In the park of Poitiers you describe leisure and habits, contrasting past and present with simple time markers. You leave able to compare what you used to do and do now.","Park of Poitiers"),
        ("Chez le marchand de vin","In a Bordeaux wine merchant's you ask for advice, express preference and quantity, and complete a guided purchase. The outcome: handle an advised, specialised purchase.","Bordeaux vineyards & wine merchants"),
        ("Au Grand Théâtre de Bordeaux","Before the Grand Théâtre you book seats, discuss a programme, and express anticipation, using the near future and opinion phrases. You can now organise an evening at a venue.","Grand Théâtre de Bordeaux"),
        ("Le long des quais de Bordeaux","On the waterfront quays you give directions across a city and describe an itinerary, narrating a short walk. The can-do: explain a route through a place you know.","Bordeaux waterfront quays"),
        ("À la Cité du Vin","Inside La Cité du Vin you describe a process and sequence steps with connectors, talking through how something is made. You leave able to explain a simple process in order.","La Cité du Vin"),
        ("Au musée des Beaux-Arts","At the Musée des Beaux-Arts you describe a work of art — its subject, colours and the feeling it gives you — your first guided aesthetic description. The outcome: describe and react to a painting.","Musée des Beaux-Arts"),
        ("Au sommet de la Dune du Pilat","Atop Europe's tallest dune you narrate an excursion in the past tense, describing the effort and the view. You can now tell the story of an outing.","Dune du Pilat"),
        ("Aux ports ostréicoles","In the oyster ports of Gujan-Mestras you talk about regional produce, order a tasting, and ask about origin and method. The can-do: discuss and order a local speciality.","Oyster ports of Gujan-Mestras"),
        ("À la cathédrale de Bayonne","Before Bayonne's Gothic cathedral you describe architecture and history simply, asking and answering questions about a monument. You leave able to talk about a historic building.","Bayonne Gothic cathedral"),
        ("Au Rocher de la Vierge","At Biarritz's Rocher de la Vierge you describe a landscape and the weather together, expressing impressions and comparisons. The outcome: paint a place in words with feeling.","Biarritz Rocher de la Vierge"),
        ("L'ascension de la Rhune","On the little train up La Rhune you narrate a journey step by step and express physical sensation, consolidating the <em>passé composé</em>. You can now recount a trip with sequence and reaction.","La Rhune"),
        ("Dans le port de Saint-Jean-de-Luz","In the harbour of Saint-Jean-de-Luz you plan a day with someone, negotiate options, and reach agreement, justifying preferences. The can-do: organise a shared day out by discussion.","Saint-Jean-de-Luz harbour"),
        ("À Espelette","In the red-pepper capital of Espelette you talk about taste, intensity and cooking, comparing flavours with simple comparatives. You leave able to describe and compare tastes.","Espelette (red pepper capital)"),
        ("Raconter le voyage","You narrate the whole Atlantic journey, chaining several past events with connectors and reactions — your most extended account yet. The outcome: tell a multi-part story of a trip.","Bordeaux waterfront quays"),
        ("Bilan — décrire, justifier, raconter","Your final unit weaves description, justification and past narration into one fluent exchange — a best-of review confirming you can now produce semi-guided language across real situations.","La Cité du Vin"),
    ],
},
"fa-intermediate": {
    "id":"fa-intermediate","name":"FA Intermediate","track":"French Atelier","track_no":"Course 4 of 4",
    "level":"A2.1 → A2.2","entry":"A2.1","exit":"A2.2","units":20,"lesson_min":"85 min","group":"8–10 learners",
    "region":"Marseille → Chamonix → Alsace & Champagne","new":True,
    "bg":"#2A1E18","accent":"#C97A4E","tint":"#EFD3BE",
    "journey":"Three contrasting corners of France in a single immersive journey.",
    "pitch":"Our newest course. From the Vieux-Port of Marseille to the glaciers of Chamonix and the Christmas markets of Alsace, you learn to defend an opinion, negotiate a compromise, and narrate with real nuance.",
    "outcome":"produce language autonomously — give and defend opinions, negotiate compromise, handle the unexpected, narrate with nuance, and compare cultures",
    "spec_schedule":"Mon & Wed evenings · live",
    "price_week":"$42","price_total":"$840",
    "geo_intro":"FA Intermediate spans three very different Frances in one journey: the sun and salt of Marseille — the Vieux-Port, Le Panier, the Calanques and the MuCEM — the high alpine drama of Chamonix and the Aiguille du Midi, and the storybook winter of Alsace and Champagne, from Strasbourg's Petite France to the chalk cellars of Reims.",
    "teachers":["stan","iris","philippe","caitlin","corentin","shanice"],
    "head":"stan",
    "next":None,
    "prev":("fa-elementary","FA Elementary","A1.2 → A2.1 · Loire → Bordeaux → Basque"),
    "signature":None,
    "lessons":[
        ("Sur le Vieux-Port de Marseille","On the Vieux-Port you reactivate opinion and learn to open a debate, expressing agreement and disagreement with nuance. The can-do: state and qualify a point of view.","Marseille Vieux-Port"),
        ("Dans les ruelles du Panier","Through Le Panier's alleyways you describe a neighbourhood and its atmosphere richly, using relative clauses with <em>qui</em> and <em>que</em>. You leave able to describe a place in connected detail.","Le Panier alleyways"),
        ("Dans les Calanques","Among the Calanques you narrate an outdoor adventure with nuance, contrasting <em>imparfait</em> and <em>passé composé</em>. The outcome: tell a layered story of an experience.","Calanques of Provence"),
        ("Au quartier de L'Estaque","In L'Estaque, painted by Cézanne, you describe and react to art and landscape, justifying an aesthetic opinion. You can now defend a taste with reasons.","L'Estaque"),
        ("Au Vallon des Auffes","At the tiny harbour of the Vallon des Auffes you handle a meal with choices and dietary needs, negotiating politely. The can-do: manage a nuanced restaurant exchange.","Vallon des Auffes"),
        ("Au MuCEM","Inside the MuCEM you compare cultures and customs, expressing similarity and difference with comparatives. You leave able to compare ways of life thoughtfully.","MuCEM"),
        ("Face au Mont-Blanc","From a viewpoint toward Mont-Blanc you express awe and hypothesis, using <em>si + présent</em> for simple conditions. The outcome: talk about possibilities and reactions.","Viewpoint toward Mont-Blanc"),
        ("Sur les glaciers de Chamonix","On the Chamonix glaciers you give and follow safety instructions and advice, using the imperative and <em>il faut</em>. You can now give and receive practical guidance.","Chamonix glaciers"),
        ("Le train de la Mer de Glace","On the rack railway to the Mer de Glace you narrate a journey with sequence and feeling, handling unexpected delays. The can-do: cope with and recount a travel hiccup.","Rack railway to the Mer de Glace"),
        ("À l'Aiguille du Midi","At 3,842 m on the Aiguille du Midi you describe sensation and reaction, expressing intensity and emotion. You leave able to convey how an extreme experience felt.","Aiguille du Midi (3,842 m)"),
        ("Dans la Petite France de Strasbourg","In Strasbourg's Petite France you ask for and give detailed recommendations, justifying and ranking options. The outcome: advise someone and defend your advice.","Strasbourg Petite France"),
        ("Au marché de Noël de la Place Broglie","At the Place Broglie Christmas market you negotiate a purchase, compare products, and express preference with nuance. You can now bargain and choose with confidence.","Place Broglie Christmas market"),
        ("Devant la cathédrale de Strasbourg","Before the pink-sandstone cathedral you describe a monument and its history in connected speech, asking deeper questions. The can-do: discuss heritage at length.","Strasbourg pink-sandstone cathedral"),
        ("Un souper au Winstub","At an Alsatian Winstub you handle a convivial meal, tell an anecdote, and react to others' stories. You leave able to take part in table conversation.","Alsatian Winstub supper"),
        ("À la cathédrale de Reims","In Reims's royal cathedral you talk about history and tradition, expressing cause and consequence with <em>parce que</em> and <em>donc</em>. The outcome: explain why things are as they are.","Reims royal cathedral"),
        ("Au marché couvert de Reims","In the indoor market of Reims you discuss regional produce and gastronomy, comparing and recommending specialities. You can now hold a food conversation with nuance.","Reims indoor market"),
        ("Sur la Place d'Erlon","On the Place d'Erlon you organise an evening with a group, negotiate compromise, and resolve disagreement. The can-do: manage a group decision diplomatically.","Place d'Erlon"),
        ("Dans les caves de Champagne","In the chalk cellars of Champagne you describe a process and tradition in detail, sequencing and explaining each stage. You leave able to talk through a complex process.","Champagne chalk cellars"),
        ("Comparer trois Frances","You compare the three regions of your journey — Mediterranean, alpine, north-eastern — expressing nuanced contrast and personal preference. The outcome: compare cultures with depth.","MuCEM"),
        ("Bilan — opinion, négociation, récit","Your final unit fuses opinion, negotiation and nuanced narration into one autonomous exchange — a best-of review confirming you can now produce language independently and handle the unexpected.","Champagne chalk cellars"),
    ],
},
"lsf-foundation": {
    "id":"lsf-foundation","name":"LSF Foundation","track":"Let's Speak French","track_no":"Speaking Track · Level 1",
    "level":"A0 → A1.1","entry":"A0","exit":"A1.1","units":10,"lesson_min":"60 min","group":"6–8 learners",
    "region":"Paris (evening, live & online)","new":False,
    "bg":"#1C1730","accent":"#E4A6B8","tint":"#F5DCE4",
    "journey":"Ten evening conversation sessions — speaking from your very first word.",
    "pitch":"Let's Speak French is all about the mouth, not the page. In ten live evening sessions you do nothing but speak — introducing yourself, ordering a drink, holding your first real exchange — in a warm small group.",
    "outcome":"introduce yourself, count, name objects, describe simply, order a drink, and hold a very short closing conversation — out loud, from day one",
    "spec_schedule":"Wed evenings · live conversation",
    "price_week":"$42","price_total":"from $42 / week",
    "geo_intro":"LSF Foundation runs parallel to FA Foundation but lives entirely in the spoken moment. Each session is a live small-group speaking room set against the rhythms of Paris — <em>sortir à Paris</em>, the playful <em>speed-dating</em> of <em>la vie à Paris</em> — built around high-frequency survival situations you'll actually say out loud.",
    "teachers":["carmele","charline","shanice","philippe"],
    "head":"carmele",
    "next":("lsf-beginner","LSF Beginner","A1.1 → A1.2 · Daily life"),
    "prev":None,
    "signature":None,
    "lessons":[
        ("Premiers mots à voix haute","In the live speaking room you say your first French words out loud — <em>bonjour</em>, your name, where you're from — repeating until they feel natural. No writing, just speaking. The can-do: introduce yourself aloud without hesitation.","Live small-group speaking room"),
        ("Compter et donner un numéro","You practise numbers by saying them — your phone, your age, a price — and check them back with a partner. The outcome: give and confirm numbers in real speech.","Live small-group speaking room"),
        ("Nommer les objets autour de soi","You name the objects and people around you, asking <em>qu'est-ce que c'est ?</em> and answering instantly. You build a spoken core vocabulary. You can now name everyday things on sight.","Live small-group speaking room"),
        ("Commander une boisson","You order a drink aloud — <em>je voudrais un café, s'il vous plaît</em> — and react to the server, rehearsing the rhythm of a café exchange. The can-do: order a drink confidently by voice.","Sortir à Paris"),
        ("Se décrire simplement","You describe yourself in a few spoken sentences — appearance, where you live, what you like — and listen to others do the same. You leave able to give a short spoken self-portrait.","Sortir à Paris"),
        ("Sortir à Paris","Role-playing a night out, you propose, accept and decline plans out loud, reacting in real time. The outcome: handle a simple spoken invitation both ways.","Sortir à Paris"),
        ("Demander et dire le prix","You ask <em>c'est combien ?</em> and answer with prices, bargaining gently in a market role-play, all spoken. You can now talk money aloud in a transaction.","Sortir à Paris"),
        ("Poser des questions simples","You drill the spoken question words — <em>où, quand, qui, comment</em> — by interviewing a partner quickly. The can-do: ask and answer simple questions in conversation.","La vie à Paris (speed dating)"),
        ("La vie à Paris — speed dating","In a fast speed-dating round you meet several partners, introducing yourself and asking questions against the clock — pure spoken fluency practice. You leave able to sustain quick first exchanges.","La vie à Paris (speed dating)"),
        ("Bilan parlé — une conversation complète","Your final session: hold one short complete conversation — greet, exchange information, order, and close politely — entirely out loud. The outcome: prove you can speak through a real micro-situation start to finish.","Live small-group speaking room"),
    ],
},
"lsf-beginner": {
    "id":"lsf-beginner","name":"LSF Beginner","track":"Let's Speak French","track_no":"Speaking Track · Level 2",
    "level":"A1.1 → A1.2","entry":"A1.1","exit":"A1.2","units":10,"lesson_min":"60 min","group":"6–8 learners",
    "region":"Daily life in France (live & online)","new":False,
    "bg":"#221A2E","accent":"#D98C9E","tint":"#F1D6DD",
    "journey":"Ten evening sessions on the spoken situations of daily French life.",
    "pitch":"You can speak your first words — now handle real daily life out loud. Ten live evening sessions drill shopping, getting around, eating out and describing your home until you respond without a script.",
    "outcome":"handle daily-life situations out loud without a script — and respond to simple unexpected prompts on the spot",
    "spec_schedule":"Tue evenings · live conversation",
    "price_week":"$42","price_total":"from $42 / week",
    "geo_intro":"LSF Beginner is the spoken companion to FA Beginner: a live small-group speaking room where the practical situations of daily life in France — shopping, getting around, eating out, describing your home and routine — become spoken reflexes rather than written rules.",
    "teachers":["shanice","iris","charline","carmele"],
    "head":"shanice",
    "next":("lsf-elementary","LSF Elementary","A1.2 → A2.1 · Settling in"),
    "prev":("lsf-foundation","LSF Foundation","A0 → A1.1 · Paris evenings"),
    "signature":None,
    "lessons":[
        ("Faire les courses à voix haute","In the speaking room you do your shopping out loud — asking for quantities, prices and produce — and react to the vendor. The can-do: complete a spoken shopping exchange.","Ordering & paying role-play"),
        ("Se déplacer en ville","You ask for and follow directions aloud, buy a ticket, and check you're on the right route. The outcome: navigate a French town by speaking.","Live small-group speaking room"),
        ("Commander et payer au restaurant","You run a full restaurant role-play — ordering courses, asking about dishes, paying — entirely by voice. You can now manage a spoken meal from start to finish.","Ordering & paying role-play"),
        ("Décrire son logement","You describe your home out loud — rooms, furniture, what you like about it — and ask others about theirs. The can-do: give a spoken description of where you live.","Describing your day"),
        ("Parler de sa routine","You talk through your daily routine aloud, sequencing actions with <em>d'abord, ensuite, après</em>. You leave able to recount a typical day in speech.","Describing your day"),
        ("Exprimer ses préférences","You say what you like and dislike out loud and justify it simply, comparing tastes with a partner. The outcome: state and defend a preference in conversation.","Live small-group speaking room"),
        ("Prendre rendez-vous","You arrange an appointment by voice — proposing times, negotiating, confirming — as in a real phone call. You can now fix a meeting out loud.","Ordering & paying role-play"),
        ("Réagir à l'imprévu","You handle spoken surprises — a closed shop, a wrong order — improvising an alternative without a script. The can-do: respond to the unexpected on the spot.","Live small-group speaking room"),
        ("Raconter sa journée","You narrate your day in the past tense aloud, chaining events and reactions in connected speech. You leave able to tell a short spoken story of what you did.","Describing your day"),
        ("Bilan parlé — la vie quotidienne","Your final session weaves shopping, travel, dining and description into one extended spoken exchange — proof you can now handle daily French life by voice, scriptless.","Ordering & paying role-play"),
    ],
},
"lsf-elementary": {
    "id":"lsf-elementary","name":"LSF Elementary","track":"Let's Speak French","track_no":"Speaking Track · Level 3",
    "level":"A1.2 → A2.1","entry":"A1.2","exit":"A2.1","units":10,"lesson_min":"60 min","group":"6–8 learners",
    "region":"Settling into French life (live & online)","new":False,
    "bg":"#2A1F1A","accent":"#CE8458","tint":"#EED5C2",
    "journey":"Ten evening sessions on the spoken realities of settling in France.",
    "pitch":"From getting by to truly belonging. Ten live evening sessions push you to give opinions, make a complaint, handle a phone appointment and read the cultural subtext — speaking with real autonomy.",
    "outcome":"produce language with real autonomy out loud and adapt your register to the situation — from a complaint to a casual chat",
    "spec_schedule":"Thu evenings · live conversation",
    "price_week":"$42","price_total":"from $42 / week",
    "geo_intro":"LSF Elementary is the spoken side of settling into French life: a live small-group speaking room where you tackle the complex situations of living in France — opinions, complaints, phone appointments, work, narration, admin and the cultural implicits — and learn to free your production from any script.",
    "teachers":["iris","stan","corentin","shanice"],
    "head":"iris",
    "next":None,
    "prev":("lsf-beginner","LSF Beginner","A1.1 → A1.2 · Daily life"),
    "signature":None,
    "lessons":[
        ("Donner son opinion","In the speaking room you give and defend opinions aloud, agreeing and disagreeing with nuance. The can-do: hold a short spoken debate.","Free production role-plays"),
        ("Faire une réclamation","You make a complaint by voice — explaining a problem, asking for a solution, staying polite but firm. The outcome: handle a spoken complaint and adapt your register.","Free production role-plays"),
        ("Prendre rendez-vous par téléphone","You manage a phone appointment aloud — without gestures or visuals, only voice — negotiating and confirming. You can now handle a real spoken phone call.","Free production role-plays"),
        ("Parler de son travail","You talk about work and study out loud, describing tasks, routines and opinions about your job. The can-do: discuss your working life in speech.","Live small-group speaking room"),
        ("Raconter une histoire","You narrate a longer story aloud, mixing past tenses and reactions to hold a listener's attention. You leave able to tell an extended spoken anecdote.","Free production role-plays"),
        ("Gérer une démarche administrative","You role-play a French admin situation by voice — a form, a counter, a request — handling its particular formality. The outcome: navigate spoken bureaucracy.","Live small-group speaking room"),
        ("Comprendre les implicites culturels","You read and respond to cultural subtext out loud — politeness, irony, indirectness — adjusting how you speak. The can-do: catch and answer what isn't said directly.","Speed dating consolidation"),
        ("Négocier et convaincre","You negotiate and try to persuade a partner aloud, building an argument and conceding gracefully. You can now argue a case in conversation.","Free production role-plays"),
        ("Speed dating de consolidation","In a fast speed-dating round you redeploy everything — opinions, stories, register — meeting partner after partner against the clock. You leave able to sustain varied spoken exchanges fluidly.","Speed dating consolidation"),
        ("Bilan parlé — production libre","Your final session is free spoken production: handle an unscripted situation from opening to close, adapting register throughout — proof you can now speak French with genuine autonomy.","Free production role-plays"),
    ],
},
}

# country-flag testimonials (tasteful: name + country + short quote) per course
TESTIMONIALS = {
"fa-foundation":[
    ("Maria","🇺🇸","United States","I learned my first French at the Eiffel Tower — well, virtually. By week three I ordered a coffee in Paris for real and was understood."),
    ("Daniel","🇨🇦","Canada","The live small group made all the difference. I'd tried apps for years; this is the first time French finally stuck."),
    ("Sophia","🇦🇺","Australia","Every lesson tied to a real place, so the words just stayed. I can navigate a café now without panicking."),
    ("Lucas","🇧🇷","Brazil","Philippe is an extraordinary teacher. Patient, funny, and the culture he weaves in makes you want to keep going."),
    ("Emma","🇬🇧","United Kingdom","I went from zero to surviving a weekend in Paris. The certificate at the end felt genuinely earned."),
    ("Noah","🇿🇦","South Africa","Twenty lessons flew by. The repair phrases alone — asking someone to slow down — saved me a hundred times."),
],
"fa-beginner":[
    ("Olivia","🇺🇸","United States","Going from Étretat to Versailles in the syllabus made the grammar feel like a journey, not a slog."),
    ("Hugo","🇧🇷","Brazil","I can finally talk about my family and my day. Caitlin's classes are warm and the pace is perfect."),
    ("Mia","🇩🇪","Germany","The market unit was so practical — I used it the next month in Lyon and the vendor smiled."),
    ("James","🇬🇧","United Kingdom","Real autonomy is the right phrase. I no longer rehearse every sentence in my head before speaking."),
    ("Chloé","🇨🇦","Canada","Honfleur, where Champlain sailed for Québec — as a Canadian that unit gave me chills."),
    ("Liam","🇮🇪","Ireland","Eight to ten people means everyone speaks. You can't hide, and that's exactly why it works."),
],
"fa-elementary":[
    ("Ava","🇺🇸","United States","Describing a painting at the Musée des Beaux-Arts in French — I never imagined I'd reach that point."),
    ("Mateo","🇲🇽","Mexico","Iris brings such nuance. I learned to justify my opinions, not just state them."),
    ("Freya","🇳🇴","Norway","The Bordeaux wine-merchant lesson was a joy. Practical, cultural, and I actually used it on holiday."),
    ("Ethan","🇨🇦","Canada","Narrating the past tense finally clicked because every story was anchored to a real trip."),
    ("Isabella","🇮🇹","Italy","From the Loire to the Basque coast — the journey structure kept me hooked for all twenty units."),
    ("Oliver","🇬🇧","United Kingdom","Semi-guided production sounds technical; in practice it just means I can hold a real conversation now."),
],
"fa-intermediate":[
    ("Charlotte","🇺🇸","United States","The newest course and worth the wait. Defending an opinion in French felt impossible — now it's natural."),
    ("Diego","🇪🇸","Spain","Three regions, three Frances. Comparing cultures gave me so much to actually talk about."),
    ("Amelia","🇳🇿","New Zealand","Stan makes the hardest grammar feel easy. The Chamonix units were unforgettable."),
    ("Henry","🇨🇦","Canada","Negotiating a compromise in French — that's a real-world skill I use at work now."),
    ("Léa","🇧🇪","Belgium","Narrating with nuance, mixing the past tenses — this is where my French finally sounded like French."),
    ("William","🇬🇧","United Kingdom","Handling the unexpected is the whole point. I'm no longer thrown when a conversation goes off-script."),
],
"lsf-foundation":[
    ("Grace","🇺🇸","United States","No textbook, just talking — terrifying at first, liberating by week two. I actually speak now."),
    ("Pedro","🇧🇷","Brazil","The speed-dating session was hilarious and the single most useful hour of French I've ever done."),
    ("Hannah","🇩🇪","Germany","Small evening group, all speaking. Carmèle makes you forget you're learning."),
    ("Felix","🇦🇹","Austria","Ordering a drink out loud, for real — that first success is addictive."),
    ("Zoe","🇬🇧","United Kingdom","I'd read French for years but couldn't say a word. This fixed exactly that."),
],
"lsf-beginner":[
    ("Ella","🇺🇸","United States","Daily-life role-plays mean I'm never lost for words in a shop or a café anymore."),
    ("Tomás","🇵🇹","Portugal","Responding to the unexpected without a script — that's the skill that changed everything."),
    ("Lina","🇸🇪","Sweden","Shanice's energy is contagious. I look forward to Tuesday evenings now."),
    ("Max","🇩🇪","Germany","Describing my flat, my routine, my day — all out loud. It finally feels like real French."),
    ("Aoife","🇮🇪","Ireland","The pure focus on speaking is exactly what every other course I tried was missing."),
],
"lsf-elementary":[
    ("Nora","🇺🇸","United States","Making a complaint in French — politely but firmly — is weirdly empowering. This course taught me register."),
    ("Marco","🇮🇹","Italy","Handling a phone appointment with no visuals, just voice, is the hardest and most useful drill."),
    ("Sara","🇪🇸","Spain","Reading the cultural subtext finally made my French feel French, not just translated English."),
    ("Tom","🇬🇧","United Kingdom","Free production role-plays push you to genuine autonomy. I can hold my own now."),
    ("Inès","🇫🇷","France (returning)","Even as a heritage speaker I gained fluency and confidence. Iris is exceptional."),
],
}
